#!/usr/bin/env python3
"""Compile a manuscript with the conference-supplied Springer SVProc class.

No model outputs, paper claims or manuscript prose are generated by this file.
The input must be a complete LaTeX source with an explicit bibliography.
"""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input", type=Path, help="Complete manuscript .tex file")
    parser.add_argument("--outdir", type=Path)
    parser.add_argument("--render-pages", action="store_true", help="Render all pages at 150 dpi for visual review")
    args = parser.parse_args()
    source = args.input.resolve()
    if not source.is_file():
        parser.error(f"Missing source: {source}")
    here = Path(__file__).resolve().parent
    styles = here / "vendor/icdlai2026/latex-package/styles"
    if not (styles / "svproc.cls").is_file():
        parser.error("Conference template is missing; restore paper/vendor/icdlai2026.")
    engine = shutil.which("tectonic")
    if not engine:
        parser.error("Tectonic is required. Install it and add it to PATH.")
    out = (args.outdir or here / "build").resolve()
    out.mkdir(parents=True, exist_ok=True)
    command = [engine, "--keep-logs", "--keep-intermediates", "--outdir", str(out)]
    for path in [source.parent, here, styles, styles / "bibtex"]:
        command += ["-Z", f"search-path={path}"]
    command += [str(source)]
    env = dict(os.environ)
    env.setdefault("SOURCE_DATE_EPOCH", "1790035200")
    result = subprocess.run(command, cwd=source.parent, env=env, text=True, capture_output=True)
    (out / "compiler_stdout.txt").write_text(result.stdout)
    (out / "compiler_stderr.txt").write_text(result.stderr)
    if result.returncode:
        sys.stderr.write(result.stdout + result.stderr)
        raise SystemExit(result.returncode)
    log_path = out / (source.stem + ".log")
    log = log_path.read_text(errors="replace") if log_path.exists() else ""
    diagnostics = {
        "input": str(source),
        "pdf": str(out / (source.stem + ".pdf")),
        "engine": subprocess.check_output([engine, "--version"], text=True).strip(),
        "overfull_boxes": re.findall(r"Overfull [^\n]+", log),
        "undefined_references": bool(re.search(r"(?:undefined references|Citation .+ undefined|Reference .+ undefined)", log)),
        "missing_characters": re.findall(r"Missing character:[^\n]+", log),
        "visual_review_required": True,
    }
    pdf = out / (source.stem + ".pdf")
    if shutil.which("pdfinfo"):
        info = subprocess.check_output(["pdfinfo", str(pdf)], text=True)
        (out / "pdfinfo.txt").write_text(info)
        diagnostics["pages"] = int(re.search(r"^Pages:\s+(\d+)", info, re.M).group(1))
        diagnostics["page_size"] = re.search(r"^Page size:\s+(.+)", info, re.M).group(1)
    if shutil.which("pdftotext"):
        subprocess.run(["pdftotext", "-layout", str(pdf), str(out / (source.stem + ".txt"))], check=True)
    if args.render_pages:
        if not shutil.which("pdftoppm"):
            parser.error("Poppler pdftoppm is required for page rendering.")
        pages = out / "pages"
        pages.mkdir(exist_ok=True)
        subprocess.run(["pdftoppm", "-r", "150", "-png", str(pdf), str(pages / "page")], check=True)
    (out / "build_diagnostics.json").write_text(json.dumps(diagnostics, indent=2) + "\n")
    print(json.dumps(diagnostics, indent=2))
    if diagnostics["undefined_references"] or diagnostics["missing_characters"]:
        raise SystemExit("Resolve missing citations/references/glyphs before using this PDF.")


if __name__ == "__main__":
    main()
